# SPDX-License-Identifier: MIT OR Apache-2.0
# Shared ccid runner; coverage selectors are explicit.
schema = 1
project = "nixdesktop"

[checks.native]
kind = "nix"
mode = "native"

[checks.eval]
kind = "nix"
mode = "eval"

[checks.list]
kind = "nix"
mode = "list"

[checks.all-systems]
kind = "nix"
mode = "all-systems"

[checks.lock-start]
kind = "commands"
commands = [["nix", "build", "--no-link", "--no-update-lock-file", "--print-build-logs", ".#checks.x86_64-linux.idle-assembly"]]
